# Usa uma imagem Node.js para o ambiente
FROM node:18

# Cria e define o diretório de trabalho
WORKDIR /app

# Copia o package.json e package-lock.json e instala as dependências
COPY package*.json ./
RUN npm install

# Copia o restante dos arquivos do projeto
COPY . .

# Expõe a porta onde o Next.js estará escutando
EXPOSE 3000

# Define o comando de inicialização
CMD ["npm", "run", "dev"]
